POST http://localhost:3000/users/create
Content-Type: application/json

{
  "username": "Seojo2",
  "password": "password123"
}

###

POST http://localhost:3000/users/clients/create
Content-Type: application/json

{
  "user_id": "60bcda0c-6171-4110-8768-e57cb10314a2"
}

###
GET http://localhost:3000/users/clients/io-token?client_id=3cdebdc8-d993-4347-852a-40ab118bd36b