POST http://localhost:3000/users/create
Content-Type: application/json

{
  "username": "Seojo1",
  "password": "password123"
}

###

POST http://localhost:3000/users/clients/create
Content-Type: application/json

{
  "user_id": "5912a40a-632a-46ef-9056-1db2842729d8"
}

###
GET http://localhost:3000/users/clients/io-token?client_id=84637327-426b-4e32-8f4a-c386aa72a8bc