POST http://localhost:3000/users/create
Content-Type: application/json

{
  "username": "Seojo1",
  "password": "password123"
}

###

POST http://localhost:3000/users/clients/create
Content-Type: application/json

{
  "user_id": "b0110034-a0a2-438d-89fc-7fb2520cce20"
}

###
GET http://localhost:3000/users/clients/io-token?client_id=760c522b-c6ad-45dc-81d3-77c60bdec542